### ISSUE TITLE
Le commit du siècle!

### ISSUE THREAD

**Issue by ShadowsWalker** [Lesterpig/yaka#2]
Bon, alors voilà, après moults efforts, j'aurai bien aimé commit mes modifs, mais seulement voilà, la console me crie dessus.

J'ai add et commit -m.
Lors du push, je mets mes identifiants et mp (ils sont bons, j'ai essayé plusieurs fois...), mais il semble que je n'ai pas le droit de push.

"
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Lesterpig/yaka.git/'
"

Je réessaye depuis un ordi autre que ceux de l'INSA...

**Comment by Lesterpig** [comment]
Résolu ?
